### ISSUE TITLE
Could not load Moq assembly.

### ISSUE THREAD

**Issue by tutukin** [autofac/Autofac.Extras.Moq#24]
In my test project:

Autofac v. 4.9.2
Autofac.Extras.Moq v.4.3.0
Moq v. 4.12.0

When running a test getting the following exception:

```
Test Name:	X_Is_Null
Test FullName:	A.B.C.Tests.ViewModelTests.X_Is_Null
Test Source:	ViewModelTests.cs : line 30
Test Outcome:	Failed
Test Duration:	0:00:00.096

Result StackTrace:	
at Autofac.Extras.Moq.AutoMock.GetLoose()
   at ViewModelTests.Constructor_Excepts_When_X_Is_Null() in ViewModelTests.cs:line 32
Result Message:	System.IO.FileLoadException : Could not load file or assembly 'Moq, Version=4.7.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Is it possible to solve the problem without downgrading the Moq to 4.7.0?

**Comment by tutukin** [comment]
Solved the following way:

1. Add app.config file to the test project root. Content may differ. I added dependencies one by one, untill all assemblies are found:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
    </configSections>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="4.2.0.0-4.8.0.0" newVersion="4.9.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Moq" publicKeyToken="69f491c39445e920" culture="neutral" />
        <bindingRedirect oldVersion="4.7.0.0" newVersion="4.12.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

To figure out the public token, find the corresponding dll and run the command:

```
powershell.exe -command "& { ([system.reflection.assembly]::loadfile(\"D:\source\workspace\MyTests\bin\x86\Debug\Autofac.dll\")).FullName}"
```

which gives the following output:

```
Autofac, Version=4.9.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da
```

2. Add app.config to the *.csproj file:

```
  <ItemGroup>
    <None Include="app.config" /> <!-- added this line -->
    <None Include="MyTests.ruleset" />  <!-- this was already there -->
  </ItemGroup>
```
